version: "3.8"

services:
  localstack:
    container_name: localstack_e2e
    image: localstack/localstack:4.14
    ports:
      - "4567:4566"
      - "4610-4659:4510-4559"
    environment:
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - EXTRA_CORS_ALLOWED_ORIGINS=*
    volumes:
      - "./.localstack_e2e:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./scripts/localstack-ready-e2e.sh:/etc/localstack/init/ready.d/localstack-ready.sh"
